# Site settings
title:         GRID 
description:    "ᲡᲞᲔᲪᲘᲤᲘᲙᲐᲪᲘᲘᲡ ᲪᲜᲝᲑᲐᲠᲘ"
baseurl: 
url: 

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Tbilisi

# Google Analytics
google_analytics:

# Author
author:
  name:         ავთო ფანგანი
  url:          https://grid.din.ge
  email:        blog@din.ge

# Build settings
markdown:       kramdown
include:
  - _pages

links:
  - title: ᲛᲗᲐᲕᲐᲠᲘ
    url: / 
  - title: ᲑᲚᲝᲒᲘ
    url: /blog
  - title: ᲩᲔᲛᲡ ᲨᲔᲡᲐᲮᲔᲑ
    url: /about
    #  - title: ᲙᲝᲜᲢᲐᲥᲢᲘ
    #    url: /contact
  
collections:
    home:
      output: true
  #  permalink: /blog/:categories/:year/:month/:day/:title.html

# Assets
sass:
  sass_dir:     /assets/css/_sass
  # style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-last-modified-at

# Permalinks
# permalink:      /:title
permalink: pretty
paginate:       5
paginate_path: "/blog/page:num"

# Excludes
exclude:
  - README.md
  - LICENSE.md

# Disqus (Set to your disqus id)
disqus:
